import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:pokedex/data/response/api_response.dart';
import 'package:pokedex/main_repository.dart';
import 'package:pokedex/model/pokeList.dart';

class HomeViewViewModel with ChangeNotifier {
  List<int> ratings = [2, 10, 1, 6, 5, 3,];
  final myRepo = HomeRepository();
  //Response loading
  ApiResponse<Autogenerated> listResponse = ApiResponse.loading();

//Setter method to pass a generic response
  setListResponse(ApiResponse<Autogenerated> response) {
    listResponse = response;
    notifyListeners();
  }

  Future<void> fetchResourcesListApi() async {
    setListResponse(ApiResponse.loading());
    myRepo.homeScreenApi().then((value) {
      setListResponse(ApiResponse.completed(value));
    }).onError((error, stackTrace) {
      if (kDebugMode) {
        setListResponse(ApiResponse.error(error.toString()));
        print(error);
      }
    });
  }
}