
import 'package:pokedex/data/app_urls.dart';
import 'package:pokedex/data/network/base_api_service.dart';
import 'package:pokedex/data/network/network_api_services.dart';
import 'package:pokedex/model/pokeList.dart';

class HomeRepository{
  BaseApiServices apiServices = NetworkApiService();
  Future<Autogenerated> homeScreenApi() async {
    dynamic response = await apiServices.getApiResponse(AppUrl.baseUrl);
    try {
      return response= Autogenerated.fromJson(response);
    } catch (e) {
      throw e;
    }
  }
}